services:
  - type: web
    name: pharmacy-dispatch-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URI
        sync: false
      - key: DB_NAME
        value: pharmacy_dispatch
      - key: ENVIRONMENT
        value: production
      - key: MOTHERDUCK_TOKEN
        sync: false
